setup: true
version: 2.1
orbs:
  continuation: circleci/continuation@0.2.0
  path-filtering: circleci/path-filtering@0.1

workflows:
  setup:
    jobs:  
      - continuation/continue:
          configuration_path: ".circleci/main.yml"
          parameters: /home/circleci/params.json
          pre-steps:
            - run:
                command: |
                  # Evaluate if Pull Request
                  if [ -z "${CIRCLE_PULL_REQUEST##*/}" ]
                  then
                    IS_PR=false
                  else
                    IS_PR=true
                  fi
                  echo '{ "is_pr": '$IS_PR' }' >> /home/circleci/params.json
                  cat /home/circleci/params.json
                  
                  # Evaluate Java Image Tag
                  ls -lsrt
                  modified_file=`git diff --name-only origin/main...$CIRCLE_SHA1 prod/digital-prison-reporting-java-template.yml | wc -l`
                  if [ ${modified_file} = 1 ]
                  then
                    JAVA_TAG="8.0"
                    echo "INFO: Triggering Build using Java Image Tag: $JAVA_TAG"
                  fi
                  echo '{ "tag": '$JAVA_TAG' }' >> /home/circleci/params.json
                  cat /home/circleci/params.json