version: 2.1

orbs:
  reporting: ministryofjustice/hmpps-reporting@dev:187d0dc359a9296b8bb2c4ebcda6a1334332470e

parameters:
  project:
    type: string
    default: ""
  release_tag: 
    type: string
    default: ""

workflows:
  release:
    jobs:            
      - reporting/generic_release:
          app: digital-prison-reporting-jobs
          sync_args: "--exclude '*' --include '*-all*jar'"
          release_ready: true
          dry_run: true
          notify_slack: false
          context:
            - hmpps-reporting-common
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
