setup: true
version: 2.1
orbs:
  continuation: circleci/continuation@0.2.0
  path-filtering: circleci/path-filtering@1.0.0

workflows:
  setup:
    jobs: 
      - clone    
      - continuation/continue:
          configuration_path: ".circleci/main.yml"
          parameters: /home/circleci/params.json
          pre-steps:
            - attach_workspace:
                at: .    
            - run:
                command: |
                  # Evaluate if Pull Request
                  if [ -z "${CIRCLE_PULL_REQUEST##*/}" ];
                  then
                    IS_PR=false
                  else
                    IS_PR=true
                  fi
                  echo '{ "is_pr": '$IS_PR'' >> /home/circleci/params.json

                  function evaluate_release {
                      echo "INFO, Release ENV: $1" 
                      if [ ${IS_PR} = true ];
                        then
                          echo "Active PR Detected, Evaluating the JOB Type..."
                          is_reporting_job=`git diff --name-only origin/main...$CIRCLE_SHA1 $1/digital-prison-reporting-jobs.yml | wc -l`
                          is_terraform_job=`git diff --name-only origin/main...$CIRCLE_SHA1 $1/digital-prison-reporting-domains.yml | wc -l`
                      elif [ ${IS_PR} = false ];
                        then
                          echo "NO Active PR Detected, Evaluating the JOB Type..."
                          is_reporting_job=`git diff --name-only origin/main..HEAD~1 $1/digital-prison-reporting-jobs.yml | wc -l`
                          is_terraform_job=`git diff --name-only origin/main..HEAD~1 $1/digital-prison-reporting-domains.yml | wc -l`
                      fi                      
                  }                   

                  if [ ${IS_PR} = true ];
                    then
                      is_prod_release=`git diff --name-only origin/main...$CIRCLE_SHA1 prod/*.yml | wc -l`
                      is_preprod_release=`git diff --name-only origin/main...$CIRCLE_SHA1 preprod/*.yml | wc -l`
                  elif [ ${IS_PR} = false ];
                    then
                      is_prod_release=`git diff --name-only origin/main..HEAD~1 prod/*.yml | wc -l`
                      is_preprod_release=`git diff --name-only origin/main..HEAD~1 preprod/*.yml | wc -l`
                  fi          

                  echo "INFO: IS_PROD_RELEASE: $is_prod_release, IS_PREPROD_RELEASE: $is_preprod_release"
                  if [ ${is_prod_release} = 1 ];
                    then
                      echo "INFO: This is a Release...."
                      is_release=true

                      # Evaluate Java Image Tag, this is required to handle different Java Versions for builds
                      # Call Function
                      evaluate_release prod

                      # Set Params 
                      if [ ${is_reporting_job} = 1 ];
                      then
                        JAVA_TAG="8.0"
                        # Pass TAG into Params File
                        echo ', "tag": "'"$JAVA_TAG"'", "project_key": "gradle" }' >> /home/circleci/params.json
                        echo "INFO: Triggering Build using Java Image Tag: $JAVA_TAG"
                      elif [ ${is_terraform_job} = 1 ];
                      then
                        echo "INFO: JAVA_TAG is set to 'default'"
                        echo ', "project_key": "terraform" }' >> /home/circleci/params.json                           
                      else
                        echo "INFO: JAVA_TAG is set to 'default'"
                        echo ', "project_key": "gradle" }' >> /home/circleci/params.json
                      fi
                  elif [ ${is_preprod_release} = 1 ];
                    then
                      echo "INFO: This is a Pre-Prod Deployment...."                      
                      is_release=false

                      # Evaluate Java Image Tag, this is required to handle different Java Versions for builds
                      # Call Function
                      evaluate_release preprod

                      # Set Params
                      if [ ${is_reporting_job} = 1 ];
                      then
                        JAVA_TAG="8.0"
                        # Pass TAG into Params File
                        echo ', "tag": "'"$JAVA_TAG"'", "project_key": "gradle" }' >> /home/circleci/params.json
                        echo "INFO: Triggering Build using Java Image Tag: $JAVA_TAG"
                      elif [ ${is_terraform_job} = 1 ];
                      then
                        echo "INFO: JAVA_TAG is set to 'default'"
                        echo ', "project_key": "terraform" }' >> /home/circleci/params.json                            
                      else
                        echo "INFO: JAVA_TAG is set to 'default'"
                        echo ', "project_key": "gradle" }' >> /home/circleci/params.json
                      fi
                  elif [ ${is_preprod_release} = 1 ] && [ ${is_prod_release} = 1 ];
                    then
                      echo "Error, Cannot Perform Release and Deploy to Preprod same Time.."
                      echo ', "skip": true }' >> /home/circleci/params.json
                  else 
                      echo "Error, Cannot Perform Release, Verify if the Config changes are specfifc to a Single Component"
                      echo ', "skip": true }' >> /home/circleci/params.json
                  fi    
                  cat /home/circleci/params.json 
          requires: [clone]        
           
jobs:
  clone:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
