setup: true
version: 2.1
orbs:
  continuation: circleci/continuation@0.2.0
  path-filtering: circleci/path-filtering@1.0.0

workflows:
  setup:
    jobs: 
      - clone    
      - continuation/continue:
          configuration_path: ".circleci/main.yml"
          parameters: /home/circleci/params.json
          pre-steps:
            - attach_workspace:
                at: .    
            - run:
                name: Generate params.json from project.yml
                command: |
                  if [ -z "${CIRCLE_PULL_REQUEST##*/}" ]; then
                    IS_PR=false
                  else
                    IS_PR=true
                  fi
                  echo '{ "is_pr": '$IS_PR'' > /home/circleci/params.json

                  function evaluate_release {
                    echo "INFO, Release ENV: $1"

                    if [ ${IS_PR} = true ]; then
                      git_range="origin/main...$CIRCLE_SHA1"
                    else
                      git_range="origin/main..HEAD~1"
                    fi

                    changed_project=$(git diff --name-only $git_range | grep -oE '^[^/]+(?=/)' | sort -u | head -n1)
                    echo "INFO: Detected changed project: $changed_project"

                    project_file="$changed_project/project.yml"
                    if [ -f "$project_file" ]; then
                      EXECUTOR=$(yq e '.executor.name' "$project_file")
                      TAG=$(yq e '.executor.tag' "$project_file")
                      PROJECT_KEY=$(yq e '.release.release_type' "$project_file")

                      echo "INFO: Using executor: $EXECUTOR, tag: $TAG, project_key: $PROJECT_KEY"

                      echo ', "is_release": '"$is_release"', "project_key": "'"$PROJECT_KEY"'", "executor": "'"$EXECUTOR"'", "tag": "'"$TAG"'" }' >> /home/circleci/params.json
                    else
                      echo "ERROR: $project_file not found"
                      echo ', "skip": true }' >> /home/circleci/params.json
                    fi
                  }

                  if [ ${IS_PR} = true ]; then
                    is_prod_release=$(git diff --name-only origin/main...$CIRCLE_SHA1 prod/*.yml | wc -l)
                    is_preprod_release=$(git diff --name-only origin/main...$CIRCLE_SHA1 preprod/*.yml | wc -l)
                  else
                    is_prod_release=$(git diff --name-only origin/main..HEAD~1 prod/*.yml | wc -l)
                    is_preprod_release=$(git diff --name-only origin/main..HEAD~1 preprod/*.yml | wc -l)
                  fi

                  echo "INFO: IS_PROD_RELEASE: $is_prod_release, IS_PREPROD_RELEASE: $is_preprod_release"

                  if [ ${is_prod_release} = 1 ]; then
                    echo "INFO: This is a Release...."
                    is_release=true
                    evaluate_release prod
                  elif [ ${is_preprod_release} = 1 ]; then
                    echo "INFO: This is a Pre-Prod Deployment...."
                    is_release=false
                    evaluate_release preprod
                  elif [ ${is_preprod_release} = 1 ] && [ ${is_prod_release} = 1 ]; then
                    echo "ERROR: Cannot perform Release and Deploy to Preprod at same time"
                    echo ', "skip": true }' >> /home/circleci/params.json
                  elif [ ${is_preprod_release} = 0 ] && [ ${is_prod_release} = 0 ]; then
                    echo "WARN: No release detected"
                    echo ', "skip": true }' >> /home/circleci/params.json
                  else 
                    echo "ERROR: Unknown state"
                    echo ', "skip": true }' >> /home/circleci/params.json
                    exit 1
                  fi

                  cat /home/circleci/params.json
          requires: [clone]        

jobs:
  clone:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install yq
          command: |
            sudo apt-get update && sudo apt-get install -y yq
      - persist_to_workspace:
          root: .
          paths:
            - .
