version: 2.1

orbs:
  reporting: ministryofjustice/hmpps-reporting@dev:2a97f6011c2941c5c598648e716a6e3f5143d7a3

parameters:
  project:
    type: string
    default: ""
  release_tag: 
    type: string
    default: ""

workflows:
  release:
    jobs:            
      - reporting/gradle_release:
          app: digital-prison-reporting-jobs
          sync_args: "--exclude '*' --include '*-all*jar'"
          release_ready: true
          dry_run: true
          notify_slack: false
          release_tag: v0.0.26
          project: digital-prison-reporting-java-template
          context:
            - hmpps-reporting-common
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
