version: 2.1

orbs:
  reporting: ministryofjustice/hmpps-reporting@dev:476224477e00ae6abbaadf7a716d5e47bc57ae0c

parameters:
  project:
    type: string
    default: ""
  release_tag: 
    type: string
    default: ""

workflows:
  release:
    jobs:            
      - reporting/gradle_release:
          app: digital-prison-reporting-jobs
          sync_args: "--exclude '*' --include '*-all*jar'"
          release_ready: true
          notify_slack: false
          release_tag: << pipeline.parameters.release_tag >>
          project: << pipeline.parameters.project >>
          context:
            - hmpps-reporting-common
          filters:
            branches:
              only: main
            tags:
              ignore: /.*/
