version: 2.1

orbs:
  reporting: ministryofjustice/hmpps-reporting@dev:fcde01adec963cdf14e8e4ef4da355428b872afa

parameters:
  project:
    type: string
    default: ""
  release_tag:
    type: string
    default: ""
  is_pr:
    type: boolean
    default: false
  tag:
    type: string
    default: "11.0"    
  is_release:
    type: string
    default: "release"   
  skip:
    description: if set to true will skip the workflow
    type: boolean
    default: false     

workflows:
  release:
    when: # Skip if the Set to True
      not: <<pipeline.parameters.skip>>
    jobs:
      - reporting/generic_release:
          sync_args: "--exclude '*' --include '*-all*jar'"
          release_ready: true
          build_args: "-x test"
          dry_run: false
          notify_slack: false
          tag: << pipeline.parameters.tag >>
          is_pr: true
          is_rollback: false
          context:
            - hmpps-reporting-common
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/