version: 2.1

orbs:
  reporting: ministryofjustice/hmpps-reporting@dev:caa46c0c8e75dd0fe9262455fe8d1c5ee76ad869

parameters:
  project:
    type: string
    default: ""
  release_tag:
    type: string
    default: ""
  is_pr:
    type: boolean
    default: false
  tag:
    type: string
    default: "11.0"    

workflows:
  release:
    jobs:
      - reporting/generic_release:
          sync_args: "--exclude '*' --include '*-all*jar'"
          release_ready: true
          build_args: "-x test"
          dry_run: false
          notify_slack: false
          tag: << pipeline.parameters.tag >>
          is_pr: << pipeline.parameters.is_pr >>
          is_rollback: true
          context:
            - hmpps-reporting-common
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/