version: 2.1

orbs:
  reporting: ministryofjustice/hmpps-reporting@dev:f2f0ad64a3fda38056c7eb6ba2accbf9b22bf106

parameters:
  project:
    type: string
    default: ""
  release_tag: 
    type: string
    default: ""
  is_pr:
    type: boolean
    default: false    

workflows:
  release:
    jobs:            
      - reporting/generic_release:
          app: digital-prison-reporting-jobs
          sync_args: "--exclude '*' --include '*-all*jar'"
          release_ready: true
          dry_run: true
          notify_slack: false
          is_pr: << pipeline.parameters.is_pr >>
          context:
            - hmpps-reporting-common
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
