version: 2.1

orbs:
  reporting: ministryofjustice/hmpps-reporting@dev:e46592bb7090e0db7dbf6d2bc38b5baf773091aa

parameters:
  project:
    type: string
    default: ""
  release_tag:
    type: string
    default: ""
  is_pr:
    type: boolean
    default: false
  executor:
    type: string
    default: 'reporting/java'
  tag:
    type: string
    default: "11.0"
  resource_class:
    type: string
    default: "large"    
  is_release:
    type: boolean
    default: false  
  skip:
    description: if set to true will skip the workflow
    type: boolean
    default: false
  sync_artifacts:
    description: Sync Artifacts to S3, Only Valid for Service Bundle
    type: boolean
    default: false    
  project_key:
    type: string
    default: ""

workflows:
  release:
    when: # Skip if the Set to True
      not: <<pipeline.parameters.skip>>
    jobs:
      - build_type
      - reporting/generic_release:
          sync_args: "--exclude '*' --include '*-all*jar'"
          release_ready: true
          build_args: "-x test"
          dry_run: false
          notify_slack: false
          skip_flyway_validate: true
          aws_sync_artifacts: << pipeline.parameters.sync_artifacts >>
          project_key: << pipeline.parameters.project_key >>
          executor: 
            name: << pipeline.parameters.executor >>
            tag: << pipeline.parameters.tag >>
            class: << pipeline.parameters.resource_class >>
          is_pr: << pipeline.parameters.is_pr >>
          is_release: << pipeline.parameters.is_release >>
          ref: << pipeline.git.branch >><< pipeline.git.tag >>
          is_rollback: false
          context:
            - hmpps-reporting-common
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
          requires: [build_type]

jobs:
  build_type:
    docker:
      - image: cimg/base:stable
    steps:
      - run: 
          name: Build Type
          command: |
            echo "INFO: Project Key, << pipeline.parameters.project_key >>"          
            echo "INFO: Downstream Executor, << pipeline.parameters.executor >>"
            echo "INFO: Downstream Image TAG, << pipeline.parameters.tag >>"
