version: 2.1

orbs:
  reporting: ministryofjustice/hmpps-reporting@dev:25b0e01e94832e77b34d42fbc69d953c8ea73f6b

parameters:
  project:
    type: string
    default: ""
  release_tag:
    type: string
    default: ""
  is_pr:
    type: boolean
    default: false
  executor:
    type: string
    default: 'reporting/java'
  tag:
    type: string
    default: "11.0"    
  is_release:
    type: string
    default: "release"   
  skip:
    description: if set to true will skip the workflow
    type: boolean
    default: false  
  project_key:
    type: string
    default: ""

workflows:
  release:
    when: # Skip if the Set to True
      not: <<pipeline.parameters.skip>>
    jobs:
      - run: 
          name: Build Type
          command: |
            echo "INFO: Project Key, << pipeline.parameters.project_key >>"          
            echo "INFO: Downstream Executor, << pipeline.parameters.executor >>"
            echo "INFO: Downstream Image TAG, << pipeline.parameters.tag >>"
      - reporting/generic_release:
          sync_args: "--exclude '*' --include '*-all*jar'"
          release_ready: true
          build_args: "-x test"
          dry_run: false
          notify_slack: false
          project_key: << pipeline.parameters.project_key >>
          executor: 
            name: << pipeline.parameters.executor >>
            tag: << pipeline.parameters.tag >>
          is_pr: << pipeline.parameters.is_pr >>
          ref: << pipeline.git.branch >><< pipeline.git.tag >>
          is_rollback: false
          context:
            - hmpps-reporting-common
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/