version: 2.1

orbs:
  reporting: ministryofjustice/hmpps-reporting@dev:b7c168595f80f48cf9645ff640bb10baa25f8ece

parameters:
  project:
    type: string
    default: ""
  release_tag:
    type: string
    default: ""
  is_pr:
    type: boolean
    default: false

workflows:
  release:
    jobs:
      - reporting/generic_release:
          sync_args: "--exclude '*' --include '*-all*jar'"
          release_ready: true
          build_args: "-x test"
          dry_run: false
          notify_slack: false
          is_pr: << pipeline.parameters.is_pr >>
          context:
            - hmpps-reporting-common
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/