name: Generate Release History in README
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  release-history:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (full history + tags)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && github.event.repository.default_branch || github.event.pull_request.head.ref || github.ref }}
          fetch-depth: 0
          fetch-tags: true

      - name: Build release history table from git tags
        id: build_table
        shell: bash
        run: |
          set -euo pipefail
          TAGS=$(git tag --sort=-creatordate | head -n 20)

          if [ -z "$TAGS" ]; then
            TABLE_ROWS="| – | – | No releases yet |"
          else
            TABLE_ROWS=""
            while IFS= read -r tag; do
              date=$(git log -1 --format=%as "$tag" 2>/dev/null || echo "—")
              subject=$(git for-each-ref "refs/tags/$tag" --format='%(subject)' 2>/dev/null)
              if [ -z "$subject" ]; then
                subject=$(git log -1 --pretty=%s "$tag" 2>/dev/null || echo "Release $tag")
              fi
              TABLE_ROWS="${TABLE_ROWS}\n| ${tag} | ${date} | ${subject} |"
            done <<< "$TAGS"
          fi

          cat > /tmp/release_block.md <<'EOF'
## 📦 Release History

<!-- RELEASE_HISTORY_START -->

| Version | Date       | Description |
|---------|------------|-------------|
EOF
          printf "%b\n" "$TABLE_ROWS" >> /tmp/release_block.md
          cat >> /tmp/release_block.md <<'EOF'

<!-- RELEASE_HISTORY_END -->

> This section is automatically updated by the release pipeline. Do not edit manually.
EOF

      - name: Inject Release History into README.md
        shell: bash
        run: |
          set -euo pipefail
          awk -v block="$(cat /tmp/release_block.md)" '
            BEGIN { in_block=0 }
            /<!-- RELEASE_HISTORY_START -->/ { print block; in_block=1; next }
            /<!-- RELEASE_HISTORY_END -->/   { in_block=0; next }
            !in_block { print }
          ' README.md > README.tmp

          if ! cmp -s README.tmp README.md; then
            mv README.tmp README.md
            echo "README updated."
          else
            echo "No changes to README."
          fi

      - name: Commit & push changes
        shell: bash
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md || true
          if git diff --cached --quiet; then
            echo "Nothing to commit."
            exit 0
          fi
          git commit -m "ci: update Release History in README [skip ci]" || true

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            git push origin "HEAD:${{ github.event.pull_request.head.ref }}"
          else
            git push origin "HEAD:${{ github.event.repository.default_branch }}"
          fi
